isentropic-dev/twine

- .gitignore
- .helix/languages.toml
- src/component.rs
- src/component/buffer.rs
- src/lib.rs
I believe using reflection to call runtime-loaded components with their required inputs and parse their computed outputs is the right approach. This method allows component developers to write components in Rust without needing to interact directly with Twine. Developers can define and use their own input and output structs (with some restrictions), while we automate the collection of the necessary metadata to replicate their data structures on the engine side.
This approach requires working with raw memory buffers, so ensuring these buffers are properly sized and aligned is critical. This PR introduces an `AlignedBuffer` trait that guarantees correct sizing and alignment, along with two concrete implementations: one for the heap and one for the stack.
> Add the concept of an aligned memory buffer

- src/component.rs
- src/component/metadata.rs
This PR introduces a `Metadata` struct that defines how a component is called. In the future we may include additional information in this metadata, such as units for physical values, valid min and max restrictions, or whether an input is a state value. But for now it focuses on providing what is needed to pass inputs to the component function and retrieve its outputs.
Resolves #3
> Add the concept of component metadata

- Cargo.lock
- twine-macros/Cargo.toml
- twine-macros/src/compose.rs
- twine-macros/src/compose/graph.rs
This PR adds `petgraph` and constructs a `DiGraph` from a slice of `ComponentInstance` objects. The core logic iterates through each component’s input fields, checking for references to other components’ output fields.
I documented the general process in the docstrings, but basically it’s just a deeply nested traversal to establish dependencies.
The next step is using this graph to determine execution order and generate the composed component’s `create` function as part of `generate::expand`.
Resolves #16 
Resolves #25
> Build a dependency graph

- Cargo.lock
- Cargo.toml
- twine-core/Cargo.toml
- twine-core/src/lib.rs
- twine-macros/Cargo.toml
This PR adds a `twine-core` crate that simply exports `twine_macros::compose`.
Once #32 is done I'll manually publish this one to crates.io.
Resolves #31
> Add a twine-core crate

- twine-macros/src/compose.rs
- twine-macros/src/compose/generate.rs
- twine-macros/tests/compose_demo.rs
- twine-macros/tests/test_components/mod.rs
This PR generates the `create` function for the composed module.  I also cleaned up the `generate` module a little bit to improve consistency in function names and docstrings.
If everything looks good with these three related PRs, I'll combine them before merging a single PR into main.
> Generate the create function

- twine-macros/src/compose.rs
- twine-macros/src/compose/generate.rs
- twine-macros/tests/compose_demo.rs
- twine-macros/tests/test_components/mod.rs
This is part two, where we use the graph to properly scope needed outputs in the generated type check function. The next, and I think final, step will be to use the graph to generate the create function.
> Use graph in type check function

- twine-macros/src/compose.rs
- twine-macros/src/compose/generate.rs
- twine-macros/src/compose/graph.rs
- twine-macros/tests/compose_demo.rs
- twine-macros/tests/test_components/mod.rs
This PR adds the `create` function to the generated code for a composed component.  The graph is used to call the components in the right order in the `impl Fn` closure that is returned by `create`.  For now this code will panic if any dependency cycles exist, but for acyclic graphs it will work regardless of the order components are declared in the `compose!` macro.
Resolves #26
> Generate the `create` function

- twine-core/src/lib.rs
The trait itself is really simple, but I thought this would be a good place to add some documentation.  Let me know if you have any suggestions for better wording or a different format.  This also includes an example that is treated as a doctest (and passes!).  I can't remember whether doctests are a good thing or if we want to disable them because they can slow down tests.  I'm fine leaving it like this or disabling them for all of `twine-core`... we can discuss next time we're chatting.
Resolves #37
> Add the Component trait

- Cargo.toml
- twine-core/Cargo.toml
I learned that there's a more direct way to manage the version dependency between published crates in this workspace. My understanding is that these two approaches are equivalent. In either case, the crates.io published `twine-core` will use that pinned `twine-macros` version, while local development will use whatever code is in the workspace, ignoring the version number. This PR uses the more direct approach, which I think is clearer than going down to the workspace toml. If we had many more crates that all referenced the same `twine-macros` version I could see the benefit of the workspace dependency, but for now I think we can keep things as simple as possible.
> Better manage the twine-macros dependency in twine-core

- .helix/languages.toml
- Cargo.lock
- Cargo.toml
- twine-components/Cargo.toml
- twine-components/src/example.rs
- twine-components/src/example/area_calculators.rs
- twine-components/src/lib.rs
- twine-core/Cargo.toml
- twine-macros/Cargo.toml
This PR adds a `twine-components` crate. I'm not sure how we'll want to organize it, but for fun I created an `example` module that has a couple area calculators. I wanted to try out the `uom` crate, and I think it's going to be perfect for components that deal with physical units.
Once we merge this into `main` I'll publish it to crates.io.
Resolves #43
ps: This PR also configures helix to autoformat TOML files.
> Add twine-components crate

- twine-core/src/context.rs
- twine-core/src/lib.rs
- twine-core/src/twine.rs
This PR adds a `Context` trait that extends `Callable` to support calling with a context and passing state through callable chains.
The idea:
- Callables extract input from a context.
- After running, they update the context using their output.
This PR also implements `Context` for `Twine<A, B>`, allowing composed callables to pass context across multiple `.then()` calls.
I added tests in the `twine` module to show how `.then()`, `.call()`, and `.call_with_context()` work.
> Add a Context trait

- twine-core/src/component.rs
- twine-core/src/component/inspect.rs
- twine-core/src/component/mapped.rs
- twine-core/src/twine.rs
- twine-core/src/twine/closure.rs
- twine-core/src/twine/then.rs
The functional approach we're taking, especially with chains of components that map their input/output for use in a bigger context, requires a `Component` to take ownership of its `Self::Input`.  I had suggested we use references in #55 but that was a misstep.  This PR puts things back how they should be.
> Components own their input

- integration-tests/tests/composed.rs
This PR puts the `composed` integration test back into place.  The only difference between this one and what's currently on `main` is adding the `TwineError` as an associated type where needed and unwrapping the `call()` result in the test.
This concludes our series of PRs that resolve #41. This was a big refactor, but I'm really happy with how it all came together.  Especially simplifying the `Twine` stuff and adding `chain()` to `Component`.  I like how that trait is evolving into something that provides all sorts of useful tools to developers working with `Component`s, that they get for free.  I think it's turning into a really clean API that we can extend for things like solving implicit equations and integrating components with state variables / derivatives.
Once all these parts are …
> Add an associated error type to Component (Part 5)

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/tests/compose_demo.rs
- twine-core/Cargo.toml
- twine-core/src/graph.rs
- twine-core/src/lib.rs
This PR creates a core `ComponentGraph` that is responsible for tracking dependencies between components.  Specifically, it tracks how a target component's input may depend on a source component's output.  The `ComponentGraph` is effectively a thin wrapper around a `petgraph::DiGraph` that provides a simplified API for adding connections between components and determining the correct call order based on those connections.  It uses `String` for component names as well as the input port label (on `Target`s) and the output port label (on `Source`s), because I want to keep it as flexible as possible.  The input/output ports on a component could be named fields (most likely) or they could be direct input/output types for simple components.  And even for named fields, that field could be nested …
> Add the concept of a component graph to twine_core

- Cargo.lock
- twine-macros/Cargo.toml
These dependencies were left over from previous iterations and should be removed.
> Remove unused dependencies in `twine-macros`

- twine-core/src/component.rs
- twine-core/src/component/mapped_err.rs
- twine-core/src/component/mapped_input.rs
- twine-core/src/component/mapped_output.rs
This PR adds two additional default methods to the `Component` trait:
- `Component::map_input()` for transforming a component's input type only.
- `Component::map_ouput()` for transforming a component's output type only.
I also cleaned up the documentation for consistency between the three type-mapping methods (these two and `Component::map_err()`) and clarified how `Component::map()` is different because it makes the new input type available in the `output_map` function, which is not possible if you were to simply chain `map_input()` and `map_output()` on a component.
> Add `Component::map_input()` and `Component::map_output()`

- twine-components/src/interpolation.rs
This simply abstracts away ninterp's extrapolation methods into our own enum.
> 76 abstract away extrapolation methods

- Cargo.lock
- Cargo.toml
- twine-examples/Cargo.toml
- twine-examples/examples/plotting.rs
- twine-plot/Cargo.toml
- twine-plot/src/lib.rs
This PR adds the `twine-plot` crate that is responsible for providing plot-based data visualization.
I wanted to start small but still demonstrate some of the `egui_plot` capabilities.  This first version is capable of plotting multiple named series of data, but the user has no control over the styling of the lines or legend.  That can come next, and I think the builder pattern will be useful here. For now I just pass whatever data is needed to add the series.
To show what the plot app looks like, you can run `cargo run --example plotting` and you'll see what it looks like to plot a couple series using `egui_plot`'s default configuration.
> Add twine-plot with minimal functionality

- Cargo.lock
- twine-components/Cargo.toml
- twine-components/src/example/oscillator.rs
- twine-components/src/lib.rs
- twine-components/src/solver.rs
- twine-components/src/solver/ode.rs
This PR adds a component that wraps `ode_solvers` to solve an `Integratable` component.  My goal was to make as few assumptions as possible to keep things flexible so users can adapt this solver component to whatever context they need.  A few interesting things fell out of this approach that I want to talk through with you, and I discovered a couple limitations of `ode_solvers` that we should discuss (the biggest being that it doesn't guarantee the final integration state lands exactly on `x_end`). This PR puts all the pieces on the board, but we may want to iterate a bit after you take a look.
> Add a component that integrates a wrapped ODE over time (Part 3)

- twine-components/src/interpolation.rs
- twine-components/src/interpolation/n.rs
Adds the ND interpolation component. Yet again, another very thin wrapper around
ninterp. This one requires a dynamically sized array. Behind the scenes, ninterp
verifies that the grid and values are dimensionally consistent.
> Adds the ND interpolation component

- Cargo.lock
- twine-components/src/fluid/ideal_gas.rs
- twine-core/Cargo.toml
- twine-core/src/lib.rs
- twine-core/src/thermo.rs
- twine-core/src/thermo/fluid.rs
- twine-core/src/thermo/units.rs
This PR adds a few more traits related to fluid property modeling (specifically to support enthalpy and entropy).  The `uom` crate doesn't have native support for these units (`J/kg` and `J/kg-K`) so I added them, along with a few other useful `Quantity`'s (units) that we'll need for #70.  I moved the `fluid` module and this new `units` module under a `thermo` namespace... I haven't given a lot of thought to how things should be organized, but it seems like these are related so this makes sense for now.  As we expand things we may want to move them around or feature-gate some (or all) of them so they're not so tightly coupled to `twine-core`.  Or maybe it will make sense to keep them here... I just don't know yet.
Another change in this PR is to improve the ideal gas fluid model slightly. …
> Expand fluid property traits and add some useful units

- twine-components/src/thermal/tank.rs
- twine-core/src/thermo/units.rs
This PR adds a `PositiveMassRate` type that wraps `MassRate` to ensure mass flow rates can't be negative. If you try to create a `PositiveMassRate` with a negative value, it will return an error.
The tank model now uses this to enforce that mass flow through the system is always positive (or zero), which matches the physical assumptions built into the energy balance.
> Add a type that enforces a non-negative `MassRate`

- twine-components/src/fluid.rs
- twine-components/src/fluid/incompressible_liquid.rs
This PR adds a fluid property model for incompressible liquids.  Full disclosure: the values for water and ethylene/propylene glycol came from an LLM.  I made #96 to track that we should double check these.
> Add fluid property model for incompressible liquids

- twine-components/src/fluid/incompressible_liquid.rs
- twine-components/src/thermal/tank.rs
- twine-core/src/thermo/units.rs
- twine-core/src/thermo/units/extensions.rs
- twine-core/src/thermo/units/positive_mass_rate.rs
- twine-core/src/thermo/units/temperature_difference.rs
This PR adds a few simple unit tests to the `thermal::tank` model.  While writing these tests I discovered some papercuts with our current `thermo::units` stuff that I tried to fix.  The major things I changed are:
- We don't need a custom `UValue` because `uom` has the equivalent thing (`HeatTransfer`).
- The `temperature_difference` function kept confusing me on the order of what subtracts from what, so I created an extension trait we can use to say `t1.minus(t2)`.  Unfortunately we can't `impl Sub` to get `t1 - t2` because of `uom` restrictions, but the `.minus(other)` is pretty ergonamic.
- I improved the `PostiveMassRate` wrapper so it can be constructed more easily.
> Add tests for `thermal::tank` model and improve `thermo::units`

- twine-core/src/transient/integrators/forward_euler.rs
- twine-core/src/transient/traits.rs
- twine-core/src/transient/transient_simulation.rs
After creating #100 I realized that we probably don't want the integrator to call the component at the next `C::Input`, because that doesn't leave a spot for us to consider controller logic (#101).  I think having the `TransientSimulation` be responsible for calling the component to get the `C::Output` it appends to the `TimeStep` history is a better design.
> Reduce integrator responsibility and leave room for a controller

- twine-core/src/transient.rs
- twine-core/src/transient/integrators/advance_time.rs
- twine-core/src/transient/integrators/forward_euler.rs
- twine-core/src/transient/traits/controller.rs
- twine-core/src/transient/traits/integrator.rs
- twine-core/src/transient/types.rs
- twine-core/src/transient/types/time_increment.rs
This PR introduces a `TimeIncrement` type that wraps `uom::si::f64::Time` and enforces strict positivity.
This ensures that all time steps move forward and improves type safety by distinguishing absolute times from time increments.
> Add a `TimeIncrement` type for advancing simulation time

- .github/workflows/ci.yml
- twine-components/src/interpolation/n.rs
- twine-components/src/interpolation/one.rs
- twine-components/src/interpolation/three.rs
- twine-components/src/interpolation/two.rs
- twine-core/src/transient.rs
- twine-core/src/transient/controllers.rs
- twine-core/src/transient/controllers/no_controller.rs
- twine-core/src/transient/controllers/pass_through.rs
- twine-core/src/transient/simulation.rs
- twine-core/src/transient/traits/controller.rs
- twine-core/src/transient/types.rs
As discussed, this PR moves `step()` back to `Simulation` while keeping `Simulation` generic only over its `Component`.  This change allows each `step` to use it's own `Integrator` and `Controller`.
Next I'll add a chainable (take `self` and return `self`) method `Simulation::advance()` that incorporates the logic we talked about to take multiple steps with a single integrator and controller.
This PR also moved away from `()` for the unit controller, since I learned that `Option<K>` can't work with `None` unless you type what would have been the `Some`.  Given that, I think being explicit with which integrator and controller to use is best, so I added the `NoController` instead of the `()` impl.
> Refactor `Simulation` to own component stepping

- twine-core/src/transient.rs
- twine-core/src/transient/integrators/forward_euler.rs
- twine-core/src/transient/simulation.rs
- twine-core/src/transient/traits.rs
- twine-core/src/transient/traits/controller.rs
- twine-core/src/transient/traits/integrator.rs
- twine-core/src/transient/traits/stateful.rs
- twine-core/src/transient/traits/temporal.rs
This PR came about because I was working on the simple "tank in a room" demo and was getting annoyed with all the type juggling I had to do with a `ThermodynamicTemperature` as the state variable. The big "aha" moment was when I realized that we shouldn't require `derivative * time = state` and also `state + state = state`.  Instead, we need `derivative * time = delta` and `state + delta = state`.  This is more flexible and works great with `uom`'s treatment of temperature types.
When implementing that change I realized I could simplify a few other trait bounds, which helped prevent "bounds pollution" from creeping into things that don't actually require them.
Here are some LLM generated notes:
- Removed the `HasTimeDerivative` trait and instead require `Div<Time>` on the state type to …
> Simplify traits and trait bounds related to transient modeling

- twine-examples/examples/tanks_in_room.rs
- twine-macros/src/lib.rs
- twine-macros/src/time_integrable.rs
This PR adds the `Derive(TimeIntegrable)` macro.  I also used it in the tanks example to verify that it works as expected.  Users have to know to suffix `Dt` when referring to the derivative struct and `_dt` on its fields, but that doesn't seem too bad considering the reduction in boilerplate it provides.
Resolves #115
> Add a `Derive(TimeIntegrable)` macro

- twine-components/src/fluid/ideal_gas.rs
- twine-components/src/fluid/incompressible_liquid.rs
- twine-components/src/thermal/tank.rs
- twine-core/src/thermo/fluid.rs
When I was looking at the published `docs.rs` stuff I realized that the fluid property trait names were pretty awkward.  This is an improvement - we may change things more in the future but for now I think this works ok.
The `PartialEq` is also a step towards "how do we verify two components are using the same fluid".  Using generics would be better, but there could always be user defined models (or even different waters at different reference conditions) so we can at least do a runtime check for equality now.
> Improve fluid property trait names

- Cargo.lock
- Cargo.toml
- twine-components/src/example/oscillator.rs
- twine-components/src/thermal/tank.rs
- twine-core/src/graph.rs
- twine-core/src/thermo/units.rs
- twine-core/src/thermo/units/positive_mass_rate.rs
- twine-examples/examples/tanks_in_room.rs
- twine-macros/src/composable.rs
- twine-macros/src/compose/extract.rs
- twine-macros/src/compose/model.rs
- twine-macros/src/compose/model/graph.rs
- twine-macros/src/compose/parse.rs
- twine-macros/src/time_integrable.rs
This PR updates the edition from 2021 to 2024, following the steps [here](https://doc.rust-lang.org/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html).
Most of the file changes are the result of the new style guide that Rust adopted for this edition.
> Update to the 2024 edition

- Cargo.lock
- twine-core/Cargo.toml
- twine-core/src/constraint.rs
- twine-core/src/constraint/non_negative.rs
- twine-core/src/constraint/non_positive.rs
- twine-core/src/constraint/non_zero.rs
- twine-core/src/constraint/strictly_negative.rs
- twine-core/src/constraint/strictly_positive.rs
- twine-core/src/lib.rs
This PR adds the `constraint` module, which is responsible for providing compile-time constraints using types.  The key concept is a generic `Constrained<T, C>` wrapper, where `C` is a `PhantomType` that defines the constraint to use.
This approach will also work for range constraints, but they'll need to be const generics (as in, at compile time I know that a value must be between `const MIN` and `const MAX`).  We could eventually have a more flexible runtime-checked constraint that uses the `std::ops::Bound` enum, but the actual values can't be checked at compile time so it's a little different.  It would still be useful though... something we can think about in the future.
I was going to start with just `NonNegative`, but I wanted to see how it would look to add others (and LLMs make …
> Add a constraint module

- Cargo.lock
- Cargo.toml
- twine-thermo/Cargo.toml
- twine-thermo/src/error.rs
- twine-thermo/src/fluid.rs
- twine-thermo/src/fluid/air.rs
- twine-thermo/src/fluid/carbon_dioxide.rs
- twine-thermo/src/fluid/custom.rs
- twine-thermo/src/fluid/custom/ideal_gas.rs
- twine-thermo/src/fluid/custom/incompressible.rs
- twine-thermo/src/fluid/water.rs
- twine-thermo/src/lib.rs
- twine-thermo/src/model.rs
- twine-thermo/src/model/ideal_gas.rs
- twine-thermo/src/model/incompressible.rs
- twine-thermo/src/model/traits.rs
- twine-thermo/src/state.rs
- twine-thermo/src/units.rs
- twine-thermo/src/units/temperature_difference.rs
This PR:
- Adds a new `twine-thermo` crate for thermodynamic property calculations
- Includes fluid models for ideal gas and incompressible fluids
- Provides traits for thermodynamic properties and state creation
- Provides preliminary support for a few fluids
The `twine_thermo::model::ideal_gas` and `twine_thermo::model::incompressible` modules have tests that provide examples of state creation and using models to get thermodynamic properties.
> Add twine-thermo crate for thermodynamic properties and modeling

- twine-core/src/constraint.rs
This PR lets us do:
```rust
let m_dot_out: Constrained<MassRate, NonNegative> = inflows.iter().map(|flow| flow.mass_rate).sum();
```
> Impl `Sum` for constrained types that support it

- twine-thermo/src/fluid/air.rs
- twine-thermo/src/fluid/carbon_dioxide.rs
- twine-thermo/src/fluid/custom/ideal_gas.rs
- twine-thermo/src/fluid/custom/incompressible.rs
- twine-thermo/src/fluid/water.rs
- twine-thermo/src/model/ideal_gas.rs
- twine-thermo/src/model/incompressible.rs
- twine-thermo/src/state.rs
This PR implements `ControlVolumeFixedFlow` for ideal gases.  I made a few other small tweaks here and there, but the main thing to check out is the implementation and tests in `model::ideal_gas`.
Next port of call is implementing `ControlVolumeConstantPressure` for ideal gases.
> Implement `ControlVolumeFixedFlow` for `IdealGas`

- twine-components/src/controller.rs
- twine-components/src/controller/thermostat.rs
- twine-components/src/controller/thermostat/heating.rs
- twine-components/src/controller/thermostat/types.rs
- twine-components/src/controller/types.rs
- twine-components/src/lib.rs
This PR adds a simple heating thermostat with a deadband.  If everything looks ok, I'll next add a `CoolingThermostat` that is nearly identical but with the logic flipped.  There might be a way to DRY those two, but for the sake of the single-responsibility principle (and my laziness...) I plan to just duplicate the component and make minimal changes to the logic and docs. Let a user import whichever one they need and not have to configure anything.
Eventually we could have an `MultiModeThermostat` or something that returns an enum of `Heat/Cool/Off` but that can come later when we have an actual need.  For now this `HeatingThermostat` should be useable in the HPWH controller.
> Add a heating thermostat controller

- twine-components/src/controller/thermostat.rs
- twine-components/src/controller/thermostat/cooling.rs
- twine-components/src/controller/thermostat/heating.rs
This PR adds a cooling-only thermostat, mirroring the `HeatingThermostat` added in #146. See that PR for discussion about potentially combining the two into a single component in the future.
> Add a cooling thermostat controller

- Cargo.lock
- Cargo.toml
- twine-components/Cargo.toml
- twine-macros/Cargo.toml
- twine-thermo/Cargo.toml
This PR increments all crates to version 0.3.0 in anticipation of manually publishing to crates.io.
I did a little research and think that we can set up a CI workflow using [cargo release](https://github.com/crate-ci/cargo-release) without much effort (for the next time we want to publish a version). There are conversations to be had about what we want our `CHANGELOG.md` to look like, but that tool supports different patterns and will probably provide some guidance on which direction we should go. My goal for version 0.4.0 is to have an established CHANGELOG and publish to crates.io through CI, so we don't need to do this manually anymore.
> Increment version to 0.3.0

- twine-core/src/constraint.rs
- twine-core/src/constraint/unit_interval.rs
This PR adds another constraint marker that is useful for restricting values to the range `[0, 1]`.  It also adds a couple variants to the `ConstraintError` that can be used to indicate if a value is invalid because it is below some min or above some max.  Currently with stable Rust it isn't possible to do something like:
```rust
struct BoundInterval<const MIN: f64, const MAX: f64>;
```
but I think that will be stablized in the future, which could be very useful as a more general constraint marker.
> Add a `UnitInterval` constraint

- twine-components/src/thermal/stratified_tank.rs
- twine-components/src/thermal/stratified_tank/port_flow.rs
This PR moves enforcement of the `PortFlow` constraint into the type itself instead of in the `new()` constructor and improves `StratifiedTank` documentation, mainly related to the concept of "port pairs" (but also other general polish).
> Refactor `PortFlow` and improve `StratifiedTank` documentation

- twine-components/src/thermal/stratified_tank.rs
- twine-components/src/thermal/stratified_tank/node.rs
This PR adds `Node`, which is private to the `stratified_tank` module and encapsulates the core heat transfer that occurs in each layer of the tank.  The `StratifiedTank` will be responsible for assembling the necessary inputs for each `dT/dt` method based on the tank configuration and an `Input` value. Since the contributions to each node's derivative are independent, we can simply sum them to get the total `dT/dt` for that node.
One nice thing that I realized while working on this is that because density and specific heat are constant, we can do all the fluid flow energy balances using just volume flow rates.
Next port of call is working on the logic that determines the incoming flow rates (and corresponding temperatures) to each node.  This will be the result of mass balances on the …
> Model heat transfer for a single node in the tank

- twine-components/src/thermal/stratified_tank.rs
- twine-components/src/thermal/stratified_tank/mass_balance.rs
This PR applies mass balances to determine the net fluid flow between nodes in the tank.  The basic idea is that each port pair can either add (inlet side) or remove (outlet side) fluid from a node.  Any imbalance in this net port flow to a node is corrected by flow from its downstairs or upstairs neighbor.  We start at the bottom node, which can only have flow to (or from) the node above it, and work our way to the top node.
Using weighted inlet/outlet arrays for the port pairs makes this approach super flexible.  For example, a port inlet (or outlet) could be applied to a single layer (e.g., a point connection) or it could be spread across multiple layers (e.g., a connection with a known height that overlaps multiple short layers when `N` is large).
Since this function is private to the …
> Apply mass balances to compute node-to-node flows

- twine-components/src/thermal/stratified_tank_new.rs
- twine-components/src/thermal/stratified_tank_new/location.rs
While working on the stratified tank example, I realized that it would be convenient to be able to place the element at a specific node.  This PR refactors the `Location` enum to allow for this, and also makes the choice between point and span more explicit (before a "point" was just a span with zero length).
> Refactor port/aux `Location` into enum

- twine-components/src/thermal/stratified_tank_new.rs
- twine-components/src/thermal/stratified_tank_new/location.rs
- twine-examples/examples/stratified_tank/main.rs
- twine-examples/examples/stratified_tank/model.rs
- twine-examples/examples/stratified_tank/plotting.rs
- twine-examples/examples/stratified_tank/simulation.rs
This is working example for the stratified tank with a single element and single port pair. There are a few places where we can make things more ergonomic, but in general it works.
One thing that this example revealed is that we should really split the `StratifiedTank::call` method into two: one that stabilizes the temperatures and another that computes the derivatives.  We can still have `call()` do both steps in one, but when you have a thermostat that uses a node temperature it is more correct to pass in the thermally stable (ie, after any possible mixing) node temperature to it.
> Add a simple stratified tank example

- twine-components/src/thermal/hx/arrangement.rs
- twine-components/src/thermal/hx/arrangement/cross_flow.rs
- twine-components/src/thermal/hx/arrangement/shell_and_tube.rs
This adds the effectiveness-NTU relations for a shell-and-tube HX.
I went with const generics here, but unfortunately there's no way to do compile time validation on some of the constraints without nightly rust. So I just went with doing the validation at construction time.
I also updated the cross-flow creation API to match what I did here for consistency.
Resolves #179
> Adds effectiveness-NTU relations for shell-and-tube
